version: '2'
services:
    kafka1:
        image:
           kafka:1.1.1
        ports:
           - 9092:9092
        networks:
           - kafka_cluster
        environment:
           - zookeeper_addr=zookeeper:2181
           - broker_id=1
           - kafka_port=9092
    zookeeper:
        image:
            registry.cn-hangzhou.aliyuncs.com/21epub/zookeeper
        ports:
           - 2181:2181
        networks:
           - kafka_cluster

networks:
   kafka_cluster:
    driver: bridge